kind = "web"
previewPath = "/"
title = "Link Page"
version = "1.0.0"
id = "artifacts/linkpage"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19486

[services.development]
run = "pnpm --filter @workspace/linkpage run dev"

[services.production]
publicDir = "artifacts/linkpage"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19486"
